### PR TITLE
Improved ROS driver

### PR DESCRIPTION
**Pull request by nowittyusername**
Hello!

As promised here's the pull request to merge the old driver with my new implementation. All questions and suggestions are welcome.

### CODE REVIEW

**Comment by 130s** [comment]
Thanks!

This adds non-trivial amount of codes so reviewers need to look into codes, regardless the fact that Travis fails because Leap's proprietary library does not get installed during CI jobs (which I started addressing in my unfinished https://github.com/ros-drivers/leap_motion/pull/35). Once that is done, I'm personally ok with merging this one w/o having CI to pass.

**Comment by nowittyusername** [comment]
Thanks for the quick response. 

I will be watching this topic closely and if you have any question about what I did, why and so on, be sure to ask.

**Comment by nowittyusername** [comment]
Are there any updates/questions regarding this pull request?

**Comment by jack-oquin** [comment]
I have no personal experience with this device, so am not qualified to review your code. It looks reasonable and seems an improvement over the previous driver, so I have no personal objection to merging it.

I am more concerned about the SDK dependency Isaac mentioned. Is there no way that can be resolved as normal using **rosdep**? The documented install method is not what users expect for an "official" ROS driver.

**Comment by nowittyusername** [comment]
Sadly I can't be the bearer of good news here.

There might be some good way to resolve that problem, because @130s was already trying to do it in #35. However I have never needed to use Travis CI so I'm too inexperienced to fix the build failure myself.

In my opinion though, even if my pull request has the same build failure as the original driver. It would still be a step towards improvement.

**Comment by jack-oquin** [comment]
I am less concerned about the Travis failure than the fact that this driver cannot  be built or released like a standard ROS driver.

Of course, solving that would also make Travis work.

I have no idea what the underlying problem with the SDK is.

**Comment by nowittyusername** [comment]
As Isaac Saito said:
>  Travis fails because Leap's proprietary library does not get installed during CI jobs

The build fails because it can't Leap.h, libLeap.so. Those files are used to access the Leap Motion controllers functionality. Now, if someone could upload the right Leap SDK files to Travis and set something to point to them during the build then I think that would be all to make Travis work.

However, I have no experience with Travis so I don't know how easy/hard that would be.

**Comment by jack-oquin** [comment]
Can the Leap SDK be released to the ROS package repositories as 3rd-party packages? Does their license allow that?

**Comment by nowittyusername** [comment]
These are their SDK terms and conditions https://central.leapmotion.com/agreements/SdkAgreement
I had a look and under "2. Distribution License"

> 2.2.2. You may not, directly or indirectly, publish, post or otherwise make available the Leap Motion Redistributables other than as compiled with, incorporated into, or packaged with, your Application.

I am not a lawyer, but I don't think it allows it to be distributed as a 3rd party package. However if we're to compile the software using it (like #35) then it should be okay as it's incorporated into my driver.

**Comment by jack-oquin** [comment]
Yeah, that's definitely not an open software license.

**Comment by nowittyusername** [comment]
I can try to see if I can resolve the #35 issue that Isaac talked about, but I won't make any promises as I have no clue about the scope of the actual problem. I have been pretty busy so I can't even give a reasonable ETA on it.

**Comment by nowittyusername** [comment]
As posted under [WIP] enable tests #35 

> I got Travis build compiling in my own repository's Travis branch, however the implementation isn't ideal. 
> I initially wanted to encrypt the location of the LeapSDK so no one could access it but Travis. However it didn't work out as intended because Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
> 
> So far I have created a simple if statement to checking if it's an outside pull request or not. You need to manually adjust the variable, but I'm hoping to find a way to do it programmatically (Soon<sup>TM</sup>). Pretty much if it's a pull request from another branch of my repo it will use my encrypted variables to pull the needed parts of the SDK from my file hosting. 
> 
> However if you want to make a pull request from forked repo you can add direct links to the needed SDK parts by adding the links into a text file. Then Travis will use wget to download the needed parts and the see if the entire thing compiles. Sadly the text files are unencrypted at the moment, but I am looking into if there's a way to have them encrypted using a public key.
> 
> When I manage to free up my schedule again I will develop the thing further. Until then you can have a look here: https://github.com/nowittyusername/leap_motion/tree/travis

**Comment by nowittyusername** [comment]
Hi!

Any update on this pull request progress?

**Comment by nowittyusername** [comment]
@130s @jack-oquin 

Hi!

I am trying to make a last effort push for this pull request for the spirit of open-source. Any update on this matter? Seeing as this repository really doesn't have an active maintainer would it be possible to just take over the maintenance? 
I don't really want to release another driver to duplicate this one, but seeing as there hasn't been any reply from the code review, I am tempted to do it.

Looking forward to the response!

P.S. Just for the hell of it, I actually wrote to Leap Motion. They said it was fine to host the parts of the SDK we need in a public repo (like this one). This should make the fixing of the CI a trivial task. https://forums.leapmotion.com/t/sdk-terms-and-conditions/7057

**Comment by 130s** [comment]
@nowittyusername 

> P.S. Just for the hell of it, I actually wrote to Leap Motion. They said it was fine to host the parts of the SDK we need in a public repo (like this one). This should make the fixing of the CI a trivial task. https://forums.leapmotion.com/t/sdk-terms-and-conditions/7057

Hey, that's a great news! Thanks for the initiative. I'll include the files in https://github.com/ros-drivers/leap_motion/pull/35 and see if CI passes.

> would it be possible to just take over the maintenance?

Absolutely! I actually asked you before in https://github.com/ros-drivers/leap_motion/issues/37 :)

**Comment by 130s** [comment]
@nowittyusername #35 is still not working as https://github.com/ros-drivers/leap_motion/pull/35#issuecomment-394140105. So for this PR of yours, you can add necessary SDK files and see how CI reacts. 

I noticed that you may have branched off from older commit because the [latest CI job](https://travis-ci.org/ros-drivers/leap_motion/builds/376239089?utm_source=github_status&utm_medium=notification) looks very different from recent jobs. You might want to first rebase to the head.

**Comment by nowittyusername** [comment]
Not that familiar with how the industrial_ci package works, but it seems I got it working. There are still some tests failing (as much as I understand), however it shouldn't be a big issue. I will see what I can do about them in the future.

Also, the reason why my CI output was a lot much different was because I used [this](https://github.com/felixduvallet/ros-travis-integration) CI implementation for my forked repository.

**Comment by nowittyusername** [comment]
If no one minds then I will merge this during the weekend.

**Comment by nowittyusername** [comment]
I think it's finally time to merge this pull request.

**Pull request merged**
