### PR TITLE
[WIP] enable tests

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by 130s** [comment]
I'm not planning to come back to this one in the near future due to my limited work time. Please anyone feel free to take over, rework, etc.

**Comment by 130s** [comment]
FYI...this PR needs proprietary SDK to be accessible somewhere programmatically (as discussed also in https://github.com/ros-drivers/leap_motion/pull/38#issuecomment-380184718). What I was thinking back then worthwhile trying was to ask LeapMotion company to allow us to access older version of SDK, as this package doesn't necessarily need the latest SDK. That would help not just CI but all users of this ROS pkg.

**Comment by nowittyusername** [comment]
So you wanted to ask Leap Motion Inc if we could distribute parts of their SDK (Leap.h, libLeap.so) in our ROS package? If I misunderstood feel free to correct me.
If that's so I wouldn't mind sending a few e-mails to ask permission to distribute parts of Leap Motion SDK v2.3.1. However I don't know if I should ask for some kind of license to prove in the future that we do in fact have permission to distribute their SDK.

Another thing I found out was that we could download the parts we need from a webserver during Travis builds. https://docs.travis-ci.com/user/encryption-keys/#Notifications-Example This would be okay with Leap licenseing terms as I am only distributing their SDK as a integrated part of my driver. However I have yet to test this in my own repository and I don't have any webhosting to provide to ROS.

**Comment by nowittyusername** [comment]
I got Travis build compiling in my own repository's Travis branch, however the implementation isn't ideal. 

I initially wanted to encrypt the location of the LeapSDK so no one could access it but Travis. However it didn't work out as intended because Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions

So far I have created a simple if statement to checking if it's an outside pull request or not. You need to manually adjust the variable, but I'm hoping to find a way to do it programmatically (Soon<sup>TM</sup>). Pretty much if it's a pull request from another branch of my repo it will use my encrypted variables to pull the needed parts of the SDK from my file hosting. 

However if you want to make a pull request from forked repo you can add direct links to the needed SDK parts by adding the links into a text file. Then Travis will use wget to download the needed parts and the see if the entire thing compiles. Sadly the text files are unencrypted at the moment, but I am looking into if there's a way to have them encrypted using a public key.

When I manage to free up my schedule again I will develop the thing further. Until then you can have a look here: https://github.com/nowittyusername/leap_motion/tree/travis

**Comment by 130s** [comment]
In https://github.com/ros-drivers/leap_motion/pull/35/commits/45011aa30eabfd93effd46a23c05e3083c8a2ac7 I added `Leap.py` from proprietary SDK, which I though was enough to be added, but CI isn't passing yet. Maybe other SDK files are needed, or even more likely is the tests I'm adding are faulty. Either way, I ran out of time to continue this PR.

**Comment by nowittyusername** [comment]
Closing this because it was already addressed in pull request #38

**Pull request closed without merging**
