### PR TITLE
Matainer email update.

### PR DESCRIPTION
**Pull request by 130s**
@nowittyusername If you can let me know your info (on this PR or offline to my email), I can include you in this PR as a maintainer.

### CODE REVIEW

**Comment by 130s** [comment]
I also disabled all tests on CI config so that CI should finally pass.

**Comment by nowittyusername** [comment]
Hey! 

I will try to look into all the other stuff in the upcoming days. For now, you can use this e-mail address for the pull request. nowittyusername@hotmail.com
As for the name you can just put _Nowittyusername_. I am this paranoid guy who doesn't really want to put his name out there unless I have reason to. 

Thanks for the update!

**Comment by 130s** [comment]
@nowittyusername You're added now to the package.xml.

@jack-oquin @mirzashah you seem to be in owners group. Could any of you add a write access to @nowittyusername for this repo? Thanks in advance.

**Comment by nowittyusername** [comment]
@jack-oquin @mirzashah any update regarding this issue?

**Comment by mirzashah** [comment]
@130s @nowittyusername -- added

**Pull request merged**
